/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#a93349',
        'secondary-fixed-dim': '#fcb973',
        'surface-container-high': '#eae8e4',
        'outline-variant': '#debfc1',
        'tertiary-fixed': '#c4e7ff',
        'surface-container': '#efeeea',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#ffb2b9',
        'on-secondary-fixed-variant': '#683c00',
        'on-primary-fixed-variant': '#891933',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f2f0ed',
        'inverse-surface': '#30312e',
        'outline': '#8a7173',
        'secondary-container': '#ffbc76',
        'on-secondary-container': '#79490b',
        'tertiary': '#00668a',
        'on-primary-container': '#6f0122',
        'on-primary-fixed': '#400010',
        'primary-fixed': '#ffdadc',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004c69',
        'on-background': '#1b1c1a',
        'background': '#fbf9f5',
        'primary': '#a93349',
        'surface': '#fbf9f5',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#003950',
        'secondary': '#855316',
        'on-error': '#ffffff',
        'on-surface': '#1b1c1a',
        'surface-bright': '#fbf9f5',
        'surface-container-highest': '#e4e2de',
        'primary-fixed-dim': '#ffb2b9',
        'primary-container': '#fb7185',
        'secondary-fixed': '#ffdcbd',
        'on-secondary-fixed': '#2c1600',
        'tertiary-container': '#04a9e3',
        'on-tertiary-fixed': '#001e2c',
        'on-surface-variant': '#574143',
        'surface-dim': '#dbdad6',
        'surface-container-low': '#f5f3ef',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-variant': '#e4e2de',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.25rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        gutter: '1rem',
        'space-xs': '0.25rem',
        margin: '1.25rem',
        'space-xl': '1.75rem',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
